# Generated by Django 4.2.7 on 2024-05-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='hash_value',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
