# Generated by Django 4.2.7 on 2024-05-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_uploadedfile_hash_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file',
            new_name='arquivo',
        ),
    ]
