# Generated by Django 4.2.7 on 2024-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_uploadedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
