# Generated by Django 4.2.7 on 2024-05-15 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_checkedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedfile',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkedfile',
            name='hash_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='checkedfile',
            name='arquivo',
            field=models.FileField(upload_to='checked/'),
        ),
    ]
