# Generated by Django 4.2.7 on 2024-05-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_checkedfile_checked_at_checkedfile_hash_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedfile',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='checkedfile',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
