# Generated by Django 4.2.7 on 2024-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_checkedfile_arquivo_checkedfile_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedfile',
            name='arquivo',
            field=models.FileField(default='teste', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
