# Generated by Django 4.2.7 on 2024-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_checkedfile_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='source',
            field=models.ManyToManyField(to='App.sources'),
        ),
    ]
