# Generated by Django 4.2.7 on 2024-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_sources_uploadedfile_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='site_fonte',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
