# Generated by Django 4.2.7 on 2024-05-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_sources_site_fonte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='source',
            new_name='Fontes',
        ),
    ]
