# Generated by Django 4.2.7 on 2024-05-16 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rename_source_uploadedfile_fontes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sources',
            old_name='site_fonte',
            new_name='web_source',
        ),
        migrations.AddField(
            model_name='sources',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
