# Generated by Django 4.2.7 on 2024-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_checkedtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedtext',
            name='Fontes',
            field=models.ManyToManyField(related_name='texto', to='App.sources'),
        ),
    ]
